"""Type stubs for pkg — Rust package manager Python API (PyO3).
Use for IDE/typechecking; point mypy/pyright to this file or copy to your project."""

from typing import Optional, Dict, List, Any, Union
from enum import IntEnum

class SolveStatus(IntEnum):
    NotSolved = 0
    Solved = 1
    Failed = 2
    def is_ok(self) -> bool: ...
    def is_error(self) -> bool: ...
    def was_attempted(self) -> bool: ...

class Action:
    Set: "Action"
    Append: "Action"
    Insert: "Action"
    Prepend: "Action"  # alias for Insert (Rez compatibility)

class Evar:
    name: str
    value: str
    action: Action
    def __init__(self, name: str, value: str, action: str = "set") -> None: ...
    def solve(self, env: "Env", max_depth: int = 10) -> "Evar": ...
    def to_dict(self) -> Dict[str, Any]: ...
    @staticmethod
    def from_dict(d: Dict[str, Any]) -> "Evar": ...

class Env:
    name: str
    evars: List[Evar]
    def __init__(self, name: str) -> None: ...
    def add(self, evar: Evar) -> None: ...
    def get(self, name: str) -> Optional[Evar]: ...
    def merge(self, other: "Env") -> "Env": ...
    def compress(self) -> "Env": ...
    def solve(self, max_depth: int = 10, use_os_fallback: bool = True) -> "Env": ...
    def commit(self) -> None: ...
    def to_dict(self) -> Dict[str, Any]: ...
    @staticmethod
    def from_dict(d: Dict[str, Any]) -> "Env": ...

class App:
    name: str
    path: Optional[str]
    args: List[str]
    env_name: Optional[str]
    cwd: Optional[str]
    def __init__(self, name: str) -> None: ...
    def with_path(self, path: str) -> "App": ...
    def to_dict(self) -> Dict[str, Any]: ...
    @staticmethod
    def from_dict(d: Dict[str, Any]) -> "App": ...

class Package:
    name: str
    base: str
    version: str
    description: Optional[str]
    reqs: List[str]
    deps: List["Package"]
    envs: List[Env]
    apps: List[App]
    tags: List[str]
    solve_status: SolveStatus
    def __init__(self, base: str, version: str) -> None: ...
    def add_env(self, env: Env) -> None: ...
    def add_app(self, app: App) -> None: ...
    def add_req(self, req: str) -> None: ...
    def default_env(self) -> Optional[Env]: ...
    def satisfies(self, constraint: str) -> bool: ...
    def to_dict(self) -> Dict[str, Any]: ...
    @staticmethod
    def from_dict(d: Dict[str, Any]) -> "Package": ...

class Storage:
    def scan() -> "Storage": ...
    @staticmethod
    def scan_paths(paths: List[str]) -> "Storage": ...
    def get(self, name: str) -> Optional[Package]: ...
    def versions(self, base: str) -> List[str]: ...
    def count(self) -> int: ...
    def has(self, name: str) -> bool: ...
    def packages(self) -> List[Package]: ...
    def list(self, tags: Optional[List[str]] = None) -> List[Package]: ...
    def latest(self, base: str) -> Optional[Package]: ...
    def resolve(self, name: str) -> Optional[Package]: ...
    def all_packages(self) -> List[Package]: ...

class Solver:
    def __init__(self, packages: List[Package]) -> None: ...
    def solve(self, request: str) -> List[str]: ...

VERSION: str
